#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const inputPath = path.resolve(__dirname, "../cel_2-45.txt");
const buildDir = path.resolve(__dirname, "../build-web");
const outputPath = path.join(buildDir, "words.generated.js");

console.log("Building words.generated.js for local development...");

const rawData = fs.readFileSync(inputPath, "utf8");
const words = rawData.split("\n").map(w => w.trim()).filter(w => w.length > 0);
console.log(`Loaded ${words.length.toLocaleString()} words`);

const wordsJson = JSON.stringify(words);
const compressed = zlib.gzipSync(Buffer.from(wordsJson, "utf8"));
const base64 = compressed.toString("base64");

const originalSize = Buffer.byteLength(wordsJson, "utf8");
const compressedSize = compressed.length;
const ratio = ((1 - compressedSize / originalSize) * 100).toFixed(1);

console.log(`Original size: ${(originalSize / 1024 / 1024).toFixed(2)} MB`);
console.log(`Compressed size: ${(compressedSize / 1024 / 1024).toFixed(2)} MB`);
console.log(`Compression ratio: ${ratio}%`);

const output = `// Auto-generated by scripts/buildWordsJS.js — do not edit by hand.
window.__LETTERFAST_WORDS__ = "${base64}";
`;

if (!fs.existsSync(buildDir)) {
    fs.mkdirSync(buildDir, { recursive: true });
}

fs.writeFileSync(outputPath, output, "utf8");
console.log(`✓ Wrote ${outputPath}`);
