#!/usr/bin/env node
// Converts words.txt into web/words.js with a cached getWords() function.
const fs = require("fs");
const path = require("path");

let inputPath = path.resolve(__dirname, "../words.txt");
let outputPath = path.resolve(__dirname, "../web/words.js");

let raw = fs.readFileSync(inputPath, "utf8");
let words = raw.split("\n").map(w => w.trim()).filter(w => w.length > 0);

let json = JSON.stringify(words);
let output = `// Auto-generated by scripts/buildWords.js — do not edit by hand.
let cachedWords;
export function getWords() {
    if (cachedWords) return cachedWords;
    cachedWords = ${json};
    return cachedWords;
}
`;

fs.writeFileSync(outputPath, output, "utf8");
console.log(`Wrote ${words.length} words to ${outputPath}`);


