#!/usr/bin/env node
// Stamps the moment of the build into a source file the bundler picks up, so
// the running app can show which build it is. Runs as the first step of
// build-web (locally via YarnWatch and in the gh-pages GitHub Action), so the
// value reflects the actual deploy time. Written under web/generated/ (which
// does NOT match the watcher's non-recursive web/*.ts glob) so regenerating it
// every build doesn't trigger an infinite rebuild loop.
const fs = require("fs");
const path = require("path");

const now = new Date();
const pad = n => String(n).padStart(2, "0");
const display =
    `${now.getUTCFullYear()}-${pad(now.getUTCMonth() + 1)}-${pad(now.getUTCDate())} ` +
    `${pad(now.getUTCHours())}:${pad(now.getUTCMinutes())} UTC`;

const outDir = path.resolve(__dirname, "../web/generated");
const outPath = path.join(outDir, "buildVersion.ts");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(
    outPath,
    `// AUTO-GENERATED by scripts/writeBuildVersion.js — do not edit.\n` +
    `export const BUILD_VERSION = ${JSON.stringify(display)};\n`,
);
console.log(`Wrote build version ${display}`);
